/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2023-06-23 02:10:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.MemberDTO;

public final class itemInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.MemberDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- ファイル名が設計通りになってると確認したらこのコメントを消してください -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ja\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<!-- 文字コード -->\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- コンテキストパス取得 -->\r\n");
      out.write("\t");
 String context = request.getContextPath();
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<title>出品登録画面</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 MemberDTO member = (MemberDTO)session.getAttribute("member"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"");
      out.print( request.getContextPath() );
      out.write("/view/UserMypage.jsp\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"マイページ\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"");
      out.print( request.getContextPath() );
      out.write("/itemInsert\"method=\"Post\"enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t商品名<input type=\"text\" name=\"itemName\"><br>\r\n");
      out.write("\t\t種類<select name=\"type\">\r\n");
      out.write("\t\t<option value=\"雑貨\">雑貨</option>\r\n");
      out.write("\t\t<option value=\"家具\">家具</option>\r\n");
      out.write("\t\t<option value=\"その他\">その他</option>\r\n");
      out.write("\t\t</select><br>\r\n");
      out.write("\t\t備考<input type=\"text\" name=\"remarks\">\r\n");
      out.write("\t\t状態<input type=\"text\" name=\"productStatus\"><br>\r\n");
      out.write("\t\t値段<input type=\"text\" name=\"price\"><br>\r\n");
      out.write("\t\t配送日数<select name=\"delivaryDay\">\r\n");
      out.write("\t\t\t<option value=\"1\" selected>1日</option>\r\n");
      out.write("  \t\t<option value=\"2\">2日</option>\r\n");
      out.write("  \t\t<option value=\"3\">三日以上</option>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t出品地域<select name=\"pref\">\r\n");
      out.write("  \t\t<option value=\"\" selected>都道府県</option>\r\n");
      out.write("  \t\t<option value=\"北海道\">北海道</option>\r\n");
      out.write("  \t\t<option value=\"青森県\">青森県</option>\r\n");
      out.write("  \t\t<option value=\"岩手県\">岩手県</option>\r\n");
      out.write("  <option value=\"宮城県\">宮城県</option>\r\n");
      out.write("  <option value=\"秋田県\">秋田県</option>\r\n");
      out.write("  <option value=\"山形県\">山形県</option>\r\n");
      out.write("  <option value=\"福島県\">福島県</option>\r\n");
      out.write("  <option value=\"茨城県\">茨城県</option>\r\n");
      out.write("  <option value=\"栃木県\">栃木県</option>\r\n");
      out.write("  <option value=\"群馬県\">群馬県</option>\r\n");
      out.write("  <option value=\"埼玉県\">埼玉県</option>\r\n");
      out.write("  <option value=\"千葉県\">千葉県</option>\r\n");
      out.write("  <option value=\"東京都\">東京都</option>\r\n");
      out.write("  <option value=\"神奈川県\">神奈川県</option>\r\n");
      out.write("  <option value=\"新潟県\">新潟県</option>\r\n");
      out.write("  <option value=\"富山県\">富山県</option>\r\n");
      out.write("  <option value=\"石川県\">石川県</option>\r\n");
      out.write("  <option value=\"福井県\">福井県</option>\r\n");
      out.write("  <option value=\"山梨県\">山梨県</option>\r\n");
      out.write("  <option value=\"長野県\">長野県</option>\r\n");
      out.write("  <option value=\"岐阜県\">岐阜県</option>\r\n");
      out.write("  <option value=\"静岡県\">静岡県</option>\r\n");
      out.write("  <option value=\"愛知県\">愛知県</option>\r\n");
      out.write("  <option value=\"三重県\">三重県</option>\r\n");
      out.write("  <option value=\"滋賀県\">滋賀県</option>\r\n");
      out.write("  <option value=\"京都府\">京都府</option>\r\n");
      out.write("  <option value=\"大阪府\">大阪府</option>\r\n");
      out.write("  <option value=\"兵庫県\">兵庫県</option>\r\n");
      out.write("  <option value=\"奈良県\">奈良県</option>\r\n");
      out.write("  <option value=\"和歌山県\">和歌山県</option>\r\n");
      out.write("  <option value=\"鳥取県\">鳥取県</option>\r\n");
      out.write("  <option value=\"島根県\">島根県</option>\r\n");
      out.write("  <option value=\"岡山県\">岡山県</option>\r\n");
      out.write("  <option value=\"広島県\">広島県</option>\r\n");
      out.write("  <option value=\"山口県\">山口県</option>\r\n");
      out.write("  <option value=\"徳島県\">徳島県</option>\r\n");
      out.write("  <option value=\"香川県\">香川県</option>\r\n");
      out.write("  <option value=\"愛媛県\">愛媛県</option>\r\n");
      out.write("  <option value=\"高知県\">高知県</option>\r\n");
      out.write("  <option value=\"福岡県\">福岡県</option>\r\n");
      out.write("  <option value=\"佐賀県\">佐賀県</option>\r\n");
      out.write("  <option value=\"長崎県\">長崎県</option>\r\n");
      out.write("  <option value=\"熊本県\">熊本県</option>\r\n");
      out.write("  <option value=\"大分県\">大分県</option>\r\n");
      out.write("  <option value=\"宮崎県\">宮崎県</option>\r\n");
      out.write("  <option value=\"鹿児島県\">鹿児島県</option>\r\n");
      out.write("  <option value=\"沖縄県\">沖縄県</option>\r\n");
      out.write("</select><br>\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"file\" name=\"image\"  size=\"60\"><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"submit\" value=\"出品開始\">\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
