/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.32
 * Generated at: 2023-06-23 02:35:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import bean.SellDTO;

public final class itemList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("bean.SellDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- http://localhost:8080/kanda_team1/view/itemList.jsp  森菜乃子-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

ArrayList<SellDTO> list = (ArrayList<SellDTO>) session.getAttribute("order_list");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ja\">\r\n");
      out.write("<head>\r\n");
      out.write("<!-- 文字コード -->\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!-- コンテキストパス取得 -->\r\n");

	String context = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>商品一覧画面</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- ログインリンク：/view/login.jsp -->\r\n");
      out.write("\t<a href=\"");
      out.print(context );
      out.write("/view/login.jsp\">ログイン</a>\r\n");
      out.write("\t\t<form action=\"");
      out.print(context);
      out.write("/searchitemlist\" method = \"get\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>商品名</td>\r\n");
      out.write("\t\t\t\t\t<td>値段（上）</td>\r\n");
      out.write("\t\t\t\t\t<td>値段（下）</td>\r\n");
      out.write("\t\t\t\t\t<td>エリア</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<!-- 商品名：product_type -->\r\n");
      out.write("\t\t\t\t\t<td><select name = \"product_type\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"雑貨\">雑貨</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"家具\">家具</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"その他\">その他</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 上限の値段：upperPrice -->\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name = \"upperPrice\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"1\">10000</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"2\">8000</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"3\">5000</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 下限の値段：lowerPrice -->\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name = \"lowerPrice\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"1\">500</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"2\">1000</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"3\">3000</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- エリア：prefectures -->\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name = \"prefectures\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"北海道\">北海道</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"青森県\">青森県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"岩手県\">岩手県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"宮城県\">宮城県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"秋田県\">秋田県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"山形県\">山形県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"福島県\">福島県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"茨城県\">茨城県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"栃木県\">栃木県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"群馬県\">群馬県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"埼玉県\">埼玉県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"千葉県\">千葉県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"東京都\">東京都</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"神奈川県\">神奈川県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"新潟県\">新潟県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"富山県\">富山県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"石川県\">石川県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"福井県\">福井県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"山梨県\">山梨県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"長野県\">長野県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"気府県\">岐阜県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"静岡県\">静岡県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"愛知県\">愛知県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"三重県\">三重県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"滋賀県\">滋賀県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"京都府\">京都府</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"大阪府\">大阪府</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"兵庫県\">兵庫県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"奈良県\">奈良県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"和歌山県\">和歌山県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"鳥取県\">鳥取県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"島根県\">島根県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"岡山県\">岡山県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"広島県\">広島県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"山口県\">山口県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"徳島県\">徳島県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"香川県\">香川県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"愛媛県\">愛媛県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"高知県\">高知県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"福岡県\">福岡県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"佐賀県\">佐賀県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"長崎県\">長崎県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"熊本県\">熊本県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"大分県\">大分県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"宮崎県\">宮崎県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"鹿児島県\">鹿児島県</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"沖縄県\">沖縄県</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<!-- 商品状態：product_condition -->\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name = \"product_condition\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"未使用\">未使用</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"使用済み\">使用済み</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value =\"傷あり\">傷あり</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<!-- 絞り込み：/searchitemlist -->\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type = \"submit\" name = \"searchitemlist\" value = \"絞り込み\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 並び替え：/searchitemlist -->\r\n");
      out.write("\t\t\t<form action=\"");
      out.print(request.getContextPath());
      out.write("/searchitemlist\" method = \"get\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 並び順：sortType -->\r\n");
      out.write("\t\t\t\t\t<select name = \"sortType\">\r\n");
      out.write("\t\t\t\t\t\t<option value =\"1\">価格が安い</option>\r\n");
      out.write("\t\t\t\t\t\t<option value =\"2\">価格が高い</option>\r\n");
      out.write("\t\t\t\t\t\t<option value =\"3\">出品日が新しい</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<input type = \"submit\" name = \"sort\" value = \"並び替え\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<table>\r\n");
      out.write("\r\n");
      out.write("\t\t");

			if (list != null) {
				for (int i = 0; i < list.size(); i++) {
					SellDTO sellDto = (SellDTO) list.get(i);
					String name=sellDto.getProductName();

		
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"");
      out.print(context);
      out.write("/productDetail?count=");
      out.print(i);
      out.write("\"><img src = \"");
      out.print( request.getContextPath() );
      out.print(sellDto.getImagePath());
      out.write("\" alt = \"なし\"></a>\r\n");
      out.write("\t\t\t\t\t\t<br><a href=\"");
      out.print(context);
      out.write("/productDetail?count=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(name );
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t<br>");
      out.print(sellDto.getPrice());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t");

				}
			}else {
		
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center; width: 200px\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center; width: 200px\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center; width: 200px\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center; width: 250px\" colspan=\"2\">&nbsp;</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
